---

version: "3"

services:
  elasticsearch:
    image: bearstech/elasticsearch:latest
    volumes:
      - ./data/elasticsearch/lib:/var/lib/elasticsearch
      - ./data/elasticsearch/log:/var/log/elasticsearch
    # user: ${UID}
    ports:
      - 9200
    hostname: elastic

  cerebro:
    image: bearstech/cerebro:latest
    links:
      - elasticsearch
    ports:
      - 9000
    user: ${UID}
    volumes:
      - ./data/cerebro:/var/lib/cerebro

  client:
    image: byrnedo/alpine-curl
    links:
      - cerebro
    entrypoint: ""
    volumes:
      - ./bin/wait-for:/usr/local/bin/wait-for
    command: >
      wait-for elasticsearch:9200 --timeout=30 --
      wait-for cerebro:9000 --timeout=30 --
      curl
      -H "Content-type: application/json"
      --silent
      -XPOST
      -v
      --connect-timeout 5
      --retry-max-time 90
      --data '{"host":"http://elasticsearch:9200"}'
      http://cerebro:9000/cluster_changes
