---

version: "3"

services:
  elasticsearch:
    image: bearstech/elasticsearch:${ELASTIC_MAJOR:-7}
    volumes:
      - ./data/elasticsearch/lib:/var/lib/elasticsearch
      - ./data/elasticsearch/log:/var/log/elasticsearch
    environment:
      DISCOVERY_TYPE: single-node
      ES_JAVA_OPTS: "-Xms500m -Xmx500m"
    ports:
      - 9200
    hostname: elastic

  cerebro:
    image: bearstech/cerebro:latest
    links:
      - elasticsearch
    ports:
      - 9000
    volumes:
      - ./data/cerebro:/var/lib/cerebro

  kibana:
    image: bearstech/kibana:${ELASTIC_MAJOR:-7}
    links:
      - elasticsearch
    ports:
      - 5601
    volumes:
      - ./data/kibana:/var/lib/kibana

  client:
    image: byrnedo/alpine-curl
    links:
      - cerebro
    entrypoint: ""
    volumes:
      - ./bin/wait-for:/usr/local/bin/wait-for
    command: >
      wait-for elasticsearch:9200 --timeout=300 --
      wait-for cerebro:9000 --timeout=300 --
      curl
      -H "Content-type: application/json"
      --silent
      -XPOST
      -v
      --connect-timeout 5
      --retry-max-time 120
      --data '{"host":"http://elasticsearch:9200"}'
      http://cerebro:9000/cluster_changes

  client_es:
    image: byrnedo/alpine-curl
    links:
      - elasticsearch
    entrypoint: ""
    volumes:
      - ./bin/wait-for:/usr/local/bin/wait-for
    command: >
      wait-for elasticsearch:9200 --timeout=300 --
      curl http://elasticsearch:9200
