FROM bearstech/debian:stretch
ARG ELASTIC_MAJOR=6

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        apt-transport-https \
        ca-certificates \
    && wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add - \
    && echo "deb https://artifacts.elastic.co/packages/oss-${ELASTIC_MAJOR}.x/apt stable main" > /etc/apt/sources.list.d/elastic-oss.list \
    && rm -rf /var/lib/apt/lists/*

